# Generated by Django 5.1.3 on 2024-12-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_city', models.CharField(max_length=50)),
                ('destination_city', models.CharField(max_length=50)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('coach_class', models.CharField(max_length=20)),
                ('total_seats', models.IntegerField(default=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ticket_code', models.CharField(editable=False, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_station', models.CharField(max_length=100)),
                ('destination_station', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('adult_count', models.PositiveIntegerField(default=1)),
                ('baby_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
