# Generated by Django 5.1.3 on 2024-12-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKAI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='arrival_date',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='coach_class',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='departure_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='destination_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='total_seats',
            field=models.IntegerField(),
        ),
    ]
