# Generated by Django 5.1.3 on 2024-12-30 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKAI', '0002_remove_ticket_arrival_date_alter_ticket_coach_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pemesan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=255)),
                ('tipe_identitas', models.CharField(max_length=10)),
                ('no_hp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Penumpang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=255)),
                ('tipe_identitas', models.CharField(max_length=10)),
                ('nomor_identitas', models.CharField(max_length=50)),
                ('pemesan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penumpang', to='appKAI.pemesan')),
            ],
        ),
    ]
