# Generated by Django 5.1.3 on 2024-12-31 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKAI', '0003_pemesan_penumpang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Belum Bayar', 'Belum Bayar'), ('Sudah Dibayar', 'Sudah Dibayar')], default='Belum Bayar', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pemesan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='appKAI.pemesan')),
                ('penumpang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='appKAI.penumpang')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='appKAI.ticket')),
            ],
        ),
    ]
