# Generated by Django 5.1.3 on 2025-01-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKAI', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
