# Generated by Django 5.1.3 on 2025-01-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKAI', '0005_order_payment_date_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='barcode_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
