# Generated by Django 5.1.3 on 2025-01-02 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appKAI', '0006_order_barcode_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='barcode_image',
        ),
    ]
