# Generated by Django 5.1.3 on 2025-01-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKAI', '0007_remove_order_barcode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
